Get http://localhost:3000/api/user/test

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json


{
    "username" : "ahmed" ,
    "email" : "ahmed@gmail.com",
    "password" : "123456"
} 

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json


{
    "email" : "ahmed@gmail.com",
    "password" : "123456"
} 

###
GET  http://localhost:3000/api/auth/signout


###
POST http://localhost:3000/api/user/update/65870c2da0681fcaebee8c3d
Content-Type: application/json


{
    "username" : "ahmed"
} 

###
DELETE http://localhost:3000/api/user/delete/65870c2da0681fcaebee8c3d


### 
POST http://localhost:3000/api/listing/create
Content-Type: application/json


{
    "name" : "test",
    "description": "test",
    "address": "test",
    "regularPrice": 200,
    "discountedPrice": 100,
    "bathrooms" : 3,
    "bedrooms": 5,
    "furnished": true,
    "parking": true,
    "type": "rent",
    "offer": true,
    "imageUrls": ["test" , "test1"],
    "userRef": "65885b165942fd1410db3268"
} 

### Get listings
GET http://localhost:3000/api/user/listings/65885b165942fd1410db3268


### delete listing
DELETE http://localhost:3000/api/listing/delete/658b1438a1775294c54bae86


### update listing
POST http://localhost:3000/api/listing/update/658b19a4467e5a7e89dd887d
Content-Type: application/json

{
    "name": "test"
}

### Get listing
GET http://localhost:3000/api/listing/get/658b19a4467e5a7e89dd887d

### search for listings
GET http://localhost:3000/api/listing/get?searchTerm=a&type=all&limit=50