Get http://localhost:3000/api/user/test

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json


{
    "username" : "ahmed" ,
    "email" : "ahmed@gmail.com",
    "password" : "123456"
} 

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json


{
    "email" : "ahmed@gmail.com",
    "password" : "123456"
} 


###
POST http://localhost:3000/api/user/update/65870c2da0681fcaebee8c3d
Content-Type: application/json


{
    "username" : "ahmed1"
} 


